2024-04-11 18:40:05,748 INFO    MainThread:8672 [wandb_setup.py:_flush():76] Configure stats pid to 8672
2024-04-11 18:40:05,748 INFO    MainThread:8672 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hugoa\.config\wandb\settings
2024-04-11 18:40:05,748 INFO    MainThread:8672 [wandb_setup.py:_flush():76] Loading settings from c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\settings
2024-04-11 18:40:05,748 INFO    MainThread:8672 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-11 18:40:05,748 INFO    MainThread:8672 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-11 18:40:05,748 INFO    MainThread:8672 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-11 18:40:05,748 INFO    MainThread:8672 [wandb_init.py:_log_setup():506] Logging user logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240411_184005-xxhbl4u0\logs\debug.log
2024-04-11 18:40:05,749 INFO    MainThread:8672 [wandb_init.py:_log_setup():507] Logging internal logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240411_184005-xxhbl4u0\logs\debug-internal.log
2024-04-11 18:40:05,749 INFO    MainThread:8672 [wandb_init.py:init():546] calling init triggers
2024-04-11 18:40:05,749 INFO    MainThread:8672 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2024-04-11 18:40:05,749 INFO    MainThread:8672 [wandb_init.py:init():568] re-initializing run, found existing run on stack: 3iqieg30
2024-04-11 18:40:05,750 INFO    MainThread:8672 [wandb_run.py:_finish():1854] finishing run hyperloopupv/5gdl/3iqieg30
2024-04-11 18:40:05,752 ERROR   MainThread:8672 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-11 18:40:05,752 INFO    MainThread:8672 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-11 18:40:05,752 INFO    MainThread:8672 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2024-04-11 18:40:05,753 INFO    MainThread:8672 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2024-04-11 18:40:05,753 INFO    MainThread:8672 [wandb_run.py:_restore():2066] restore
2024-04-11 18:40:05,753 INFO    MainThread:8672 [wandb_run.py:_restore():2072] restore done
2024-04-11 18:40:13,762 INFO    MainThread:8672 [wandb_init.py:init():602] starting backend
2024-04-11 18:40:13,762 INFO    MainThread:8672 [wandb_init.py:init():606] setting up manager
2024-04-11 18:40:13,765 INFO    MainThread:8672 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2024-04-11 18:40:13,768 INFO    MainThread:8672 [wandb_init.py:init():613] backend started and connected
2024-04-11 18:40:13,769 INFO    MainThread:8672 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2024-04-11 18:40:13,769 INFO    MainThread:8672 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-11 18:40:13,769 INFO    MainThread:8672 [wandb_init.py:init():701] updated telemetry
2024-04-11 18:40:13,925 INFO    MainThread:8672 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
